### ISSUE TITLE
Some js file in library of magento 2 doesn't compatible

### ISSUE THREAD

**Issue by ppeyman** [breezefront/theme-frontend-breeze-evolution#11]
Hi dears i have to to add some js code to our module and saw some js functions doesn't load in breeze for example :
```
isEmpty
restArguments
isObject
isNull
isUndefined

```

some function In many of modules or js files called like below for example : 

```
 if (name.match(reMin) && result && !$.mage.isEmpty(v)) {
                            length = name.split('-')[2];
                            result = v.length >= length;
                            validator.validateMessage =
                                $.__('Please enter more than or equal to %1 digits.').replace('%1', length);
                        }
```

I checked these function are in below file who doesn't load in breeze theme
 ex: evolution : 
**lib>web> underscore.js**

How can i Solve problem ?

**Comment by ppeyman** [comment]
> Just use underscore in your files:
> 
> ```js
> _.isEmpty();
> _.restArguments()
> ```
> 
> https://breezefront.com/globals

i tried and give below error on console :( :  
```
request.js:240 Uncaught TypeError: this[(params.method || "get")] is not a function
    at Object.send (request.js:240:48)
    at $.ajax (request.js:268:26)
    at HTMLButtonElement.<anonymous> (profile-phone-validation.js:125:23)
    at HTMLButtonElement.Ra (cash-8.1.2.min.js:28:374)
```

**Comment by vovayatsyuk** [comment]
Sorry, but it's not clear what are you trying to do. Can you attach your code?

**Comment by vovayatsyuk** [comment]
Oh, I see. Replace all `method: "POST"` lines with `method: "post"`.

**Comment by ppeyman** [comment]
shows another error:
```
profile-phone-validation.js:135 Uncaught TypeError: $.ajax(...).done is not a function
    at HTMLButtonElement.<anonymous> (profile-phone-validation.js:135:24)
    at HTMLButtonElement.Ra (cash-8.1.2.min.js:28:374)
```

**Comment by ppeyman** [comment]
> Replace it with `.then()` or `success: function()`

I solved many of lines
a new one i don't know why show again error 
:( 

is there any way it works with old js file ? 
i should change 20 files with this rules.

new error :

```
TypeError: $(...).delay is not a function
    at Object.success (profile-phone-validation.js:137:56)
    at onSuccess (request.js:40:20)
    at request.js:222:28
```

**Comment by vovayatsyuk** [comment]
We do not have delay function. Remove it or replace with native setTimeout.

**Comment by ppeyman** [comment]
> We do not have delay function. Remove it or replace with native setTimeout.

where can i find function who works with breeze ?

**Comment by vovayatsyuk** [comment]
https://breezefront.com/globals

**Comment by vovayatsyuk** [comment]
> is there any way who it works with old js file ?

No, but it's not critical since the new code is compatible with jQuery and you may use the changed file in both Luma and Breeze.

**Comment by ppeyman** [comment]
> > is there any way who it works with old js file ?
> 
> No, but it's not critical since the new code is compatible with jQuery and you may use the changed file in both Luma and Breeze.


However, many functions and property doesn't work on Breeze system and must have an alternative.
Like:
after
length 
blur
siblings
show
change

**Comment by vovayatsyuk** [comment]
Show me examples for each of these functions and I'll try to show you breeze and luma compatible notation.

**Comment by ppeyman** [comment]
ok 
For change : 
```
$('#reset_type').change(function(){
                var mdForgotPassword = $(".md-forget-password");
                if ($(this).val() === 'Email') {
                    $(mdForgotPassword).find(".field.mobile").hide();
                    $(mdForgotPassword).find(".field.mobile #mobile_number").val("");
                    $(mdForgotPassword).find(".field.email").show();
                    $(mdForgotPassword).find('.actions-toolbar.reset-pwd').show();
                    $(mdForgotPassword).find('.actions-toolbar.reset-pwd button span').html('Send Email');
                } else {
                    $(mdForgotPassword).find(".field.mobile").show();
                    $(mdForgotPassword).find(".field.email").hide();
                    $(mdForgotPassword).find(".field.email #email_address").val("");
                    $(mdForgotPassword).find('.actions-toolbar.reset-pwd').hide();
                    $(mdForgotPassword).find('.actions-toolbar.reset-pwd button span').html('Reset Password');
                }
            });
```

for after : 
` $('.customer-account-edit #customer_mobile').after('<div class="profile-notice-phone"> <span>'+$(".note").val()+'</span> </div> <button class="send_otp_edit_ee action primary" style="margin-top: 15px; display:none" type="button">Generate OTP</button');`

for length:
```
if($(document).find(".smserror").length > 0 ) {
                    $(document).find(".smserror").html('');
                }
```
for blur : 

```
$('#customer_mobile').blur(function() {
                var form = $(this).closest('form');

                if ($(this).val() != '') {
                    if (!$(this).val()) {
                        $(form).find('.send_otp').hide();
                        $(form).find('.actions-toolbar button.action.submit.primary').attr("disabled", false);
                    } else {
                        $(form).find('.send_otp').show();
                        $(form).find('.actions-toolbar button.action.submit.primary').attr("disabled", true);
                    }
                }    
            });
```

show : 

`$(document).find('.send_otp_login').show();`


Thank you!

**Comment by ppeyman** [comment]
> Show me examples for each of these functions and I'll try to show you breeze and luma compatible notation.

dear @vovayatsyuk i solved another one just change method i don't know how to solve it

**Comment by vovayatsyuk** [comment]
Original | Replacement
-----------|-------------------
$('#reset_type').change(..) | $('#reset_type').on('change', ..)
$('#reset_type').blur(..) | $('#reset_type').on('focusout', ..)

Other methods should work fine.
